In [39]:
import numpy as np
import pandas as pd
import regex as re

In [40]:
attacks = pd.read_csv("attacks.csv", encoding = "latin_1", sep = ",")
attacks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [41]:
attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [42]:
attacks.drop(columns = ["Unnamed: 22", "Unnamed: 23"], inplace = True)

In [43]:
attacks.dropna(how = "all", inplace = True)

In [44]:
attacks.dropna(thresh = 0.1*len(attacks.columns), inplace = True)

In [45]:
attacks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             6301 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6302 non-null   float64
dtypes: float64(2), object(20)
memory usage: 1.1+ MB

In [51]:
pd.options.display.max_columns = 30
pd.options.display.max_rows = 6300

In [46]:
attacks["Country"].value_counts()

USA                                      2229
AUSTRALIA                                1338
SOUTH AFRICA                              579
PAPUA NEW GUINEA                          134
NEW ZEALAND                               128
BRAZIL                                    112
BAHAMAS                                   109
MEXICO                                     89
ITALY                                      71
FIJI                                       62
PHILIPPINES                                61
REUNION                                    60
NEW CALEDONIA                              53
CUBA                                       46
MOZAMBIQUE                                 45
SPAIN                                      44
INDIA                                      40
EGYPT                                      38
CROATIA                                    34
JAPAN                                      34
PANAMA                                     32
SOLOMON ISLANDS                            30
IRAN                                       29
JAMAICA                                    27
FRENCH POLYNESIA                           25
GREECE                                     25
HONG KONG                                  24
INDONESIA                                  23
ENGLAND                                    23
PACIFIC OCEAN                              17
ATLANTIC OCEAN                             17
COSTA RICA                                 17
BERMUDA                                    16
VIETNAM                                    15
TONGA                                      15
SRI LANKA                                  14
VANUATU                                    14
MARSHALL ISLANDS                           13
FRANCE                                     13
CANADA                                     12
SOUTH ATLANTIC OCEAN                       12
TURKEY                                     12
IRAQ                                       12
VENEZUELA                                  11
UNITED KINGDOM                             11
SENEGAL                                    11
KENYA                                      10
NEW GUINEA                                 10
MAURITIUS                                  10
ECUADOR                                     9
TAIWAN                                      9
COLUMBIA                                    9
CARIBBEAN SEA                               8
TANZANIA                                    8
SCOTLAND                                    8
MADAGASCAR                                  8
CHILE                                       8
SOUTH KOREA                                 8
THAILAND                                    8
SAMOA                                       8
SIERRA LEONE                                8
SEYCHELLES                                  7
NORTH PACIFIC OCEAN                         7
ISRAEL                                      7
CHINA                                       7
DOMINICAN REPUBLIC                          7
YEMEN                                       7
INDIAN OCEAN                                7
LIBYA                                       6
BARBADOS                                    6
OKINAWA                                     6
NICARAGUA                                   6
NEW BRITAIN                                 6
SOMALIA                                     6
KIRIBATI                                    6
SINGAPORE                                   6
PALAU                                       5
MALAYSIA                                    5
MALTA                                       5
AZORES                                      5
TURKS & CAICOS                              5
MID ATLANTIC OCEAN                          5
SAUDI ARABIA                                5
BURMA                                       4
NORTH ATLANTIC OCEAN                        4
PERSIAN GULF                                4
EL SALVADOR                                 4
URUGUAY                                     4
SUDAN                                       4
GRENADA                                     4
HONDURAS                                    4
GUAM                                        4
NIGERIA                                     4
RUSSIA                                      4
MONTENEGRO                                  3
CEYLON                                      3
TRINIDAD & TOBAGO                           3
MARTINIQUE                                  3
 TONGA                                      3
BELIZE                                      3
GUINEA                                      3
AMERICAN SAMOA                              3
PORTUGAL                                    3
Fiji                                        3
TUNISIA                                     3
LEBANON                                     3
GUYANA                                      3
MICRONESIA                                  3
HAITI                                       3
LIBERIA                                     3
CAPE VERDE                                  3
YEMEN                                       2
UNITED ARAB EMIRATES                        2
WEST INDIES                                 2
EGYPT                                       2
ICELAND                                     2
CRETE                                       2
SOUTHWEST PACIFIC OCEAN                     2
SOUTH PACIFIC OCEAN                         2
JOHNSTON ISLAND                             2
NORWAY                                      2
CAYMAN ISLANDS                              2
CENTRAL PACIFIC                             2
UNITED ARAB EMIRATES (UAE)                  2
ST HELENA, British overseas territory       2
PACIFIC OCEAN                               2
NAMIBIA                                     2
TOBAGO                                      2
ANTIGUA                                     2
MEDITERRANEAN SEA                           2
SAN DOMINGO                                 1
RED SEA?                                    1
REUNION ISLAND                              1
CYPRUS                                      1
IRELAND                                     1
KUWAIT                                      1
ASIA?                                       1
MONACO                                      1
FALKLAND ISLANDS                            1
INDIAN OCEAN?                               1
PARAGUAY                                    1
EQUATORIAL GUINEA / CAMEROON                1
ALGERIA                                     1
Coast of AFRICA                             1
TASMAN SEA                                  1
GHANA                                       1
AFRICA                                      1
PERU                                        1
GREENLAND                                   1
SWEDEN                                      1
COOK ISLANDS                                1
ROATAN                                      1
BRITISH NEW GUINEA                          1
ANDAMAN ISLANDS                             1
Between PORTUGAL & INDIA                    1
TUVALU                                      1
DJIBOUTI                                    1
SYRIA                                       1
GEORGIA                                     1
BAHREIN                                     1
OCEAN                                       1
KOREA                                       1
ITALY / CROATIA                             1
COMOROS                                     1
CURACAO                                     1
SLOVENIA                                    1
BRITISH ISLES                               1
WESTERN SAMOA                               1
BANGLADESH                                  1
SOUTH CHINA SEA                             1
ANGOLA                                      1
NORTHERN ARABIAN SEA                        1
EGYPT / ISRAEL                              1
MEXICO                                      1
Seychelles                                  1
GRAND CAYMAN                                1
ST. MAARTIN                                 1
Sierra Leone                                1
GULF OF ADEN                                1
BRITISH VIRGIN ISLANDS                      1
NEVIS                                       1
MALDIVES                                    1
PALESTINIAN TERRITORIES                     1
DIEGO GARCIA                                1
ST. MARTIN                                  1
PUERTO RICO                                 1
ARUBA                                       1
RED SEA                                     1
FEDERATED STATES OF MICRONESIA              1
ADMIRALTY ISLANDS                           1
ARGENTINA                                   1
MID-PACIFC OCEAN                            1
BAY OF BENGAL                               1
SOLOMON ISLANDS / VANUATU                   1
 PHILIPPINES                                1
JAVA                                        1
IRAN / IRAQ                                 1
NORTHERN MARIANA ISLANDS                    1
NETHERLANDS ANTILLES                        1
GUATEMALA                                   1
SUDAN?                                      1
BRITISH WEST INDIES                         1
THE BALKANS                                 1
NORTH ATLANTIC OCEAN                        1
MAYOTTE                                     1
GABON                                       1
ANDAMAN / NICOBAR ISLANDAS                  1
MALDIVE ISLANDS                             1
NICARAGUA                                   1
NORTH SEA                                   1
RED SEA / INDIAN OCEAN                      1
CEYLON (SRI LANKA)                          1
Name: Country, dtype: int64

In [52]:
attacks.head(6302)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,BRA x USA
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,USA
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,USA
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,USA
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,USA
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN